version: "3.8"
services:
    bot:
        build: .
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        volumes:
            - ./data:/app/data # For SQLite persistence
